# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('simple-udp-application-example', ['simple-udp-application'])
    obj.source = 'simple-udp-application-example.cc'

